### ISSUE TITLE
Bug, R38, Use of FRE command after RESET and OLD creates endless loop

### ISSUE THREAD

**Issue by JustinBaldock** [commanderx16/x16-emulator#369]
I think I may have discovered a bug. Just hoping to see if other people can replicate? I'm using a Virtual Windows 10 machine.

Create any BASIC program. 

10 PRINT"TEST"
20 GOTO 10

Then use the RESET command, use the OLD command then try PRINT FRE(0)

The emulator locked up with what appears to be an endless loop. Errors are going to the CMD console are 

WARN: Invalid register 9fbc
WARN: Invalid register 9fb6
WARN: Invalid register 9fbc
WARN: Invalid register 9fbc

Bug was replicated by another user, JimmyDansbo, slightly different invalid warnings.
WARN: Invalid register 9fb7
WARN: Invalid register 9fbc
WARN: Invalid register 9fb6

**Comment by irmen** [comment]
Just tried it, and this problem is still present in the new r39 version.

**Comment by mist64** [comment]
The problem is that the host filesystem interface is a giant hack: It hooks `LOAD` and `SAVE`, then reads and writes magic memory locations. Instead, we should hook `OPEN`, `CHKIN`, `CKOUT`, `BASIN`, `BSOUT`. This will solve all these problems and remove a lot of code duplication (like banking logic).

**Comment by mist64** [comment]
Should be fixed by e84dc1b. Can you verify?

**Comment by irmen** [comment]
got a compiler error unfortunately
``cc -std=c99 -O3 -Wall -Werror -g -I/usr/include/SDL2 -D_REENTRANT -Isrc/extern/include -Isrc/extern/src -c src/main.c -o build/main.o
src/main.c: In function ‘set_kernal_status’:
src/main.c:891:1: error: type of ‘s’ defaults to ‘int’ [-Werror=implicit-int]
  891 | set_kernal_status(s)
      | ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:74: build/main.o] Error 1
``

**Comment by mist64** [comment]
Warning should be fixed by 212f949.

**Comment by irmen** [comment]
Yup it compiles again, but I still see 
WARN: Invalid register 9fb7
WARN: Invalid register 9fb6
WARN: Invalid register 9fb7
WARN: Invalid register 9fbc
WARN: Invalid register 9fb6
WARN: Invalid register 9fbc

after doing that sequence of commands in the original post. I'm on Manjaro Linux.
